export const data = [
  // initial packets
  "encryption_begin",
  "compress",
  "success",
  "login",
  "custom_payload",
  "difficulty",
  "abilities",
  "held_item_slot",
  "declare_recipes",
  "tags",
  "entity_status",
  "entity_status",
  "unlock_recipes",
  "position",
  "player_info",
  "update_view_position",
  "update_view_distance",
  "initialize_world_border",
  "spawn_position",
  "update_health",
  "experience",
  "advancements",
  "declare_commands",
  // other packets
  "map_chunk",
  "update_light",
  "block_change",
  "world_event",
  "multi_block_change",
  "playerlist_header",
  "rel_entity_move",
  "update_time",
  "spawn_entity_living",
  "window_items",
  "spawn_entity",
  "entity_move_look",
  "entity_head_rotation",
  "entity_teleport",
  "entity_metadata",
  "entity_update_attributes",
  "entity_equipment",
  "entity_velocity",
  "entity_look",
  "entity_destroy",

  // already listened
  // "chat",
  // "kick_disconnect",
  // "disconnect",

  "keep_alive"
];
